### ISSUE TITLE
Error when accessing Dean's Permission Report

### ISSUE THREAD

**Issue by AaravMehta4897** [mxschool/mxMoodle#81]
<img width="1131" alt="Screen Shot 2021-06-26 at 11 05 17 AM" src="https://user-images.githubusercontent.com/58570210/123517367-83bed380-d66e-11eb-801c-2ae4ca8c146d.png">

**Comment by MXchuck** [comment]
I have not been able to recreate this; let's do it together.

**Comment by MXchuck** [comment]
Hmm, This might be related to Issue #83 and #82.
Let's fix those first and revisit this with a fresh install.
